<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Application\IntegratedProcurement.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Domain\IntegratedProcurement.Modules.ContractMonitoring.Domain.csproj" />
    <ProjectReference Include="..\..\..\Platform\Notifications\Application\IntegratedProcurement.Platform.Notifications.Application.csproj" />
    <ProjectReference Include="..\..\..\Platform\Documents\Application\IntegratedProcurement.Platform.Documents.Application.csproj" />
    <ProjectReference Include="..\..\..\Platform\Audit\Application\IntegratedProcurement.Platform.Audit.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
