// <auto-generated />
using System;
using IntegratedProcurement.Platform.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegratedProcurement.Platform.Persistence.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    [Migration("20260915093528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntegratedProcurement.Platform.Administration.Domain.ApplicationAboutEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("P_K_A_P_P_L_I_C_A_T_I_O_N_A_B_O_U_T_T");

                    b.ToTable("APPLICATION_ABOUT_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Administration.Domain.EmailSentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Category");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("MessageId");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("SentAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Status");

                    b.HasKey("Id")
                        .HasName("P_K_E_M_A_I_L_S_E_N_T_T");

                    b.HasIndex("Category")
                        .HasDatabaseName("I_X_E_M_A_I_L_S_E_N_T_T_CATEGORY");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("I_X_E_M_A_I_L_S_E_N_T_T_MESSAGE_ID");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("I_X_E_M_A_I_L_S_E_N_T_T_SENT_AT");

                    b.HasIndex("Status")
                        .HasDatabaseName("I_X_E_M_A_I_L_S_E_N_T_T_STATUS");

                    b.ToTable("EMAIL_SENT_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Administration.Domain.EmailTemplateEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Status");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("TemplateId");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("P_K_E_M_A_I_L_T_E_M_P_L_A_T_E_T");

                    b.HasIndex("Category")
                        .HasDatabaseName("I_X_E_M_A_I_L_T_E_M_P_L_A_T_E_T_CATEGORY");

                    b.HasIndex("TemplateId")
                        .IsUnique()
                        .HasDatabaseName("I_X_E_M_A_I_L_T_E_M_P_L_A_T_E_T_TEMPLATE_ID");

                    b.ToTable("EMAIL_TEMPLATE_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Administration.Domain.LanguageEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("P_K_L_A_N_G_U_A_G_E_T");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("I_X_L_A_N_G_U_A_G_E_T_CODE");

                    b.ToTable("LANGUAGE_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Administration.Domain.LanguageTextEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<string>("TextKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TextKey");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("P_K_L_A_N_G_U_A_G_E_T_E_X_T_T");

                    b.HasIndex("TextKey")
                        .IsUnique()
                        .HasDatabaseName("I_X_L_A_N_G_U_A_G_E_T_E_X_T_T_TEXT_KEY");

                    b.ToTable("LANGUAGE_TEXT_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Administration.Domain.MasterDataRecordEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Name");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ParentCode");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<string>("SetKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SetKey");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("P_K_M_A_S_T_E_R_D_A_T_A_R_E_C_O_R_D_T");

                    b.HasIndex("SetKey")
                        .HasDatabaseName("I_X_M_A_S_T_E_R_D_A_T_A_R_E_C_O_R_D_T_SET_KEY");

                    b.HasIndex("Status")
                        .HasDatabaseName("I_X_M_A_S_T_E_R_D_A_T_A_R_E_C_O_R_D_T_STATUS");

                    b.HasIndex("SetKey", "Code")
                        .IsUnique()
                        .HasDatabaseName("I_X_M_A_S_T_E_R_D_A_T_A_R_E_C_O_R_D_T_SET_KEY_CODE");

                    b.HasIndex("SetKey", "ParentCode")
                        .HasDatabaseName("I_X_M_A_S_T_E_R_D_A_T_A_R_E_C_O_R_D_T_SET_KEY_PARENT_CODE");

                    b.ToTable("MASTER_DATA_RECORD_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Administration.Domain.MasterDataSetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit")
                        .HasColumnName("IsReadOnly");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Owner");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TableName");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("P_K_M_A_S_T_E_R_D_A_T_A_S_E_T_T");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("I_X_M_A_S_T_E_R_D_A_T_A_S_E_T_T_KEY");

                    b.ToTable("MASTER_DATA_SET_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Administration.Domain.MenuTreeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("MenuKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MenuKey");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("P_K_M_E_N_U_T");

                    b.HasIndex("MenuKey")
                        .IsUnique()
                        .HasDatabaseName("I_X_M_E_N_U_T_MENU_KEY");

                    b.ToTable("MENU_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Audit.Domain.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Action");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ActorName");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("IpAddress");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MetadataJson");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Module");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("OccurredAt");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("UserAgent");

                    b.HasKey("Id")
                        .HasName("P_K_A_U_D_I_T_L_O_G_T");

                    b.HasIndex("ActorName")
                        .HasDatabaseName("I_X_A_U_D_I_T_L_O_G_T_ACTOR_NAME");

                    b.HasIndex("Module")
                        .HasDatabaseName("I_X_A_U_D_I_T_L_O_G_T_MODULE");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("I_X_A_U_D_I_T_L_O_G_T_OCCURRED_AT");

                    b.ToTable("AUDIT_LOG_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("IsSystem");

                    b.Property<string>("ModuleKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModuleKey");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("P_K_R_O_L_E_T");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("I_X_R_O_L_E_T_CODE");

                    b.ToTable("ROLE_T", "iam");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalRolePermissionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PermissionId");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.HasKey("Id")
                        .HasName("P_K_R_O_L_E_P_E_R_M_I_S_S_I_O_N_T");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("I_X_R_O_L_E_P_E_R_M_I_S_S_I_O_N_T_PERMISSION_ID");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("I_X_R_O_L_E_P_E_R_M_I_S_S_I_O_N_T_ROLE_ID_PERMISSION_ID");

                    b.ToTable("ROLE_PERMISSION_T", "iam");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("AccessFailedCount");

                    b.Property<string>("CompleteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CompleteName");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Department");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LockoutEnd");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ManagerUserId");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit")
                        .HasColumnName("MustChangePassword");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<DateTimeOffset?>("PasswordSetAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("PasswordSetAt");

                    b.Property<string>("PersonnelNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PersonnelNo");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Position");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("SecurityStamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id")
                        .HasName("P_K_U_S_E_R_T");

                    b.HasIndex("ManagerUserId")
                        .HasDatabaseName("I_X_U_S_E_R_T_M_A_N_A_G_E_R");

                    b.HasIndex("PersonnelNo")
                        .IsUnique()
                        .HasDatabaseName("I_X_U_S_E_R_T_PERSONNEL_NO")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("USER_T", "iam", t =>
                        {
                            t.HasCheckConstraint("CK_USER_T_STATUS", "[Status] IN ('Active','Inactive','Suspended')");
                        });
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("P_K_U_S_E_R_R_O_L_E_T");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("I_X_U_S_E_R_R_O_L_E_T_ROLE_ID");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("I_X_U_S_E_R_R_O_L_E_T_USER_ID_ROLE_ID");

                    b.ToTable("USER_ROLE_T", "iam");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.InternalIdentity.Domain.PermissionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Key");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModuleKey");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("P_K_P_E_R_M_I_S_S_I_O_N_T");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("I_X_P_E_R_M_I_S_S_I_O_N_T_KEY");

                    b.ToTable("PERMISSION_T", "iam");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Notifications.Domain.NotificationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("AudienceLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AudienceLabel");

                    b.Property<string>("AudienceRoles")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("AudienceRoles");

                    b.Property<string>("AudienceScope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AudienceScope");

                    b.Property<string>("AudienceUser")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AudienceUser");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Detail");

                    b.Property<string>("LinkPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LinkPath");

                    b.Property<string>("Module")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Module");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Title");

                    b.HasKey("Id")
                        .HasName("P_K_N_O_T_I_F_I_C_A_T_I_O_N_T");

                    b.HasIndex("AudienceScope")
                        .HasDatabaseName("I_X_N_O_T_I_F_I_C_A_T_I_O_N_T_AUDIENCE_SCOPE");

                    b.HasIndex("AudienceUser")
                        .HasDatabaseName("I_X_N_O_T_I_F_I_C_A_T_I_O_N_T_AUDIENCE_USER");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("I_X_N_O_T_I_F_I_C_A_T_I_O_N_T_CREATED_AT");

                    b.ToTable("NOTIFICATION_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Notifications.Domain.NotificationRecipientState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DismissedAt");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NotificationId");

                    b.Property<string>("PersonnelNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("PersonnelNo");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ReadAt");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("P_K_N_O_T_I_F_I_C_A_T_I_O_N_R_E_C_I_P_I_E_N_T_S_T_A_T_E_T");

                    b.HasIndex("PersonnelNo")
                        .HasDatabaseName("I_X_N_O_T_I_F_I_C_A_T_I_O_N_R_E_C_I_P_I_E_N_T_S_T_A_T_E_T_PERSONNEL_NO");

                    b.HasIndex("NotificationId", "PersonnelNo")
                        .IsUnique()
                        .HasDatabaseName("I_X_N_O_T_I_F_I_C_A_T_I_O_N_R_E_C_I_P_I_E_N_T_S_T_A_T_E_T_NOTIFICATION_ID_PERSONNEL_NO");

                    b.ToTable("NOTIFICATION_RECIPIENT_STATE_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Persistence.FrontendState.FrontendStateEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Key");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Scope");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.HasKey("Id")
                        .HasName("P_K_F_R_O_N_T_E_N_D_S_T_A_T_E_T");

                    b.HasIndex("Scope", "Key")
                        .IsUnique()
                        .HasDatabaseName("I_X_F_R_O_N_T_E_N_D_S_T_A_T_E_T_SCOPE_KEY");

                    b.ToTable("FRONTEND_STATE_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Persistence.ModuleState.ModuleStateEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModuleKey");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("StorageKey");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("P_K_M_O_D_U_L_E_S_T_A_T_E_T");

                    b.HasIndex("ModuleKey", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("I_X_M_O_D_U_L_E_S_T_A_T_E_T_MODULE_KEY_STORAGE_KEY");

                    b.ToTable("MODULE_STATE_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.Settings.Domain.SettingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValueJson");

                    b.HasKey("Id")
                        .HasName("P_K_S_E_T_T_I_N_G_T");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("I_X_S_E_T_T_I_N_G_T_KEY");

                    b.ToTable("SETTING_T", "core");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalRolePermissionAssignment", b =>
                {
                    b.HasOne("IntegratedProcurement.Platform.InternalIdentity.Domain.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("F_K_R_O_L_E_P_E_R_M_I_S_S_I_O_N_T_P_E_R_M_I_S_S_I_O_N_T_PERMISSION_ID");

                    b.HasOne("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("F_K_R_O_L_E_P_E_R_M_I_S_S_I_O_N_T_R_O_L_E_T_ROLE_ID");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalUser", b =>
                {
                    b.HasOne("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalUser", null)
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("F_K_U_S_E_R_T_U_S_E_R_T_MANAGER_USER_ID");
                });

            modelBuilder.Entity("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalUserRole", b =>
                {
                    b.HasOne("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("F_K_U_S_E_R_R_O_L_E_T_R_O_L_E_T_ROLE_ID");

                    b.HasOne("IntegratedProcurement.Platform.InternalIdentity.Domain.InternalUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("F_K_U_S_E_R_R_O_L_E_T_U_S_E_R_T_USER_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
